# Generated by Django 2.1.15 on 2023-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
